version: "3"

services:
  solr:
    image: solr
    hostname: solr
    container_name: solr-container
    restart: on-failure
    ports:
      - "8983:8983"
    volumes:
      - ./configs:/var/solr/data
    command:
      - solr-precreate
      - gettingstarted
